# See here for image contents:
# https://github.com/microsoft/vscode-dev-containers/tree/v0.209.6/containers/go/.devcontainer/base.Dockerfile

FROM rust:1.76.0

RUN useradd --create-home --shell /bin/bash dev

USER dev

